#!/usr/bin/env python3
"""Generate assets/TEMPLATE_INDEX.yaml from assets/templates/.

Usage:
    python scripts/build_template_index.py

Reads every .tsv file under assets/templates/, extracts the SAP table code and
object name from the filename, and emits assets/TEMPLATE_INDEX.yaml — a flat
list of records keyed by table_code for fast agent lookup.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

SKILL_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = SKILL_ROOT / "assets" / "templates"
OUTPUT = SKILL_ROOT / "assets" / "TEMPLATE_INDEX.yaml"


def parse_filename(name: str) -> tuple[str, str]:
    """Return (table_code, object_name) from a DTW template filename.

    Expected format: `<TABLE_CODE> - <ObjectName>.tsv`
    Examples:
        OCRD - BusinessPartners.tsv       → ('OCRD', 'BusinessPartners')
        CRD1 - BPAddresses.tsv           → ('CRD1', 'BPAddresses')
        IGE1 - Document_Lines.tsv        → ('IGE1', 'Document_Lines')
    """
    stem = Path(name).stem  # remove .tsv
    match = re.match(r"^([A-Z@][A-Z0-9_@#]*)\s*-\s*(.+)$", stem)
    if match:
        return match.group(1).strip(), match.group(2).strip()
    # Fallback: no separator pattern
    return stem, stem


def collect_entries() -> list[dict]:
    entries = []
    for tsv in sorted(TEMPLATES_DIR.rglob("*.tsv")):
        rel = tsv.relative_to(TEMPLATES_DIR)
        parts = rel.parts  # ('Module', 'Sub / Category', ..., 'TABLE - Name.tsv')
        table_code, object_name = parse_filename(tsv.name)

        module = parts[0] if len(parts) >= 1 else ""
        subpath_parts = list(parts[1:-1])  # zero or more intermediate dirs
        category = " / ".join(subpath_parts) if subpath_parts else module

        entries.append(
            {
                "table_code": table_code,
                "object_name": object_name,
                "module": module,
                "category": category,
                "path": str(rel).replace("\\", "/"),
            }
        )
    return entries


def main() -> None:
    if not TEMPLATES_DIR.exists():
        raise SystemExit(f"ERROR: templates directory not found: {TEMPLATES_DIR}")

    entries = collect_entries()
    print(f"Found {len(entries)} template files")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        f.write(
            "# DTW Template Index — auto-generated by scripts/build_template_index.py\n"
        )
        f.write("# Keys: table_code, object_name, module, category, path\n")
        yaml.dump(
            entries, f, allow_unicode=True, sort_keys=False, default_flow_style=False
        )

    print(f"Written → {OUTPUT.relative_to(SKILL_ROOT)}")


if __name__ == "__main__":
    main()
